name: Continuous Integration

on:
  push:
    branches: [ main, latest ]

env:
  BUILD_VERSION: 3.0.${{github.run_number}}

jobs:
  build-core:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build and Push Image
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: wiki-core
        tags: dev-${{env.BUILD_VERSION}}
        registry: ghcr.io
        dockerfile: dev/docker/core.dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract build
      uses: shrink/actions-docker-extract@v1
      id: extract
      with:
        image: ghcr.io/requarks/wiki-core:dev-${{env.BUILD_VERSION}}
        path: /wiki-core/.
    - name: Create Archive
      run: tar -czf wiki-core.tar.gz ${{ steps.extract.outputs.destination }}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: core
        path: wiki-core.tar.gz
  build-ui:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build and Push Image
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: wiki-ui
        tags: dev-${{env.BUILD_VERSION}}
        registry: ghcr.io
        dockerfile: dev/docker/ui.dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract build
      uses: shrink/actions-docker-extract@v1
      id: extract
      with:
        image: ghcr.io/requarks/wiki-ui:dev-${{env.BUILD_VERSION}}
        path: /wiki-ui/.
    - name: Create Archive
      run: tar -czf wiki-ui.tar.gz ${{ steps.extract.outputs.destination }}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ui
        path: wiki-ui.tar.gz
  build-combo:
    needs: [build-core, build-ui]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@0.1.4
      with:
        include: dev/combo/combo.dockerfile
        find: __BUILD_VERSION__
        replace: ${{env.BUILD_VERSION}}
    - name: Build and Push Image
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: wiki-combo
        tags: dev-${{env.BUILD_VERSION}}
        registry: ghcr.io
        dockerfile: dev/combo/combo.dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    needs: [build-core, build-ui]
    runs-on: windows-latest
    steps:
      - name: Download Build Artifacts
        id: download
        uses: actions/download-artifact@v2.0.10
        with:
          path: ${{env.GITHUB_WORKSPACE}}/artifacts
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Rebuild Core Dependencies
        run: |
          tar xfz wiki-core.tar.gz
          rm wiki-core.tar.gz
          npm rebuild
        working-directory: ${{steps.download.outputs.download-path}}\core
      - name: Rebuild UI Dependencies
        run: |
          tar xfz wiki-ui.tar.gz
          rm wiki-ui.tar.gz
          npm rebuild
        working-directory: ${{steps.download.outputs.download-path}}\ui
      - name: Create Archive
        run: tar -czvf windows.tar.gz ${{steps.download.outputs.download-path}}\
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windows
          path: windows.tar.gz
  publish-beta:
    if: ${{ github.ref == 'refs/heads/latest' }}
    needs: [build-combo, build-windows]
    runs-on: ubuntu-latest
    environment: beta
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Dev Images
      run: |
        docker pull ghcr.io/requarks/wiki-core:dev-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-ui:dev-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-combo:dev-${{env.BUILD_VERSION}}
    - name: Tag Beta Images
      run: |
        docker tag ghcr.io/requarks/wiki-core:dev-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-ui:dev-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-combo:dev-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}}
    - name: Push Beta Images
      run: |
        docker push ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}}
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2.0.10
      with:
        path: ${{env.GITHUB_WORKSPACE}}/artifacts
    - name: Create Archives
      run: |
        mv ./windows/windows.tar.gz ./windows.tar.gz
        tar -czf core.tar.gz core/
        tar -czf ui.tar.gz ui/
      working-directory: artifacts
    - name: Generate Changelog
      uses: Bullrich/generate-release-changelog@master
      id: changelog
      env:
        REPO: ${{ github.repository }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "core/wiki-core.tar.gz,ui/wiki-ui.tar.gz,windows/windows.tar.gz"
        body: |
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: true
        tag: ${{env.BUILD_VERSION}}
        token: ${{ secrets.GITHUB_TOKEN }}
  publish-release:
    if: ${{ github.ref == 'refs/heads/latest' }}
    needs: [publish-beta]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Parse semver
      id: semver
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{env.BUILD_VERSION}}
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull Beta Images
      run: |
        docker pull ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}}
        docker pull ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}}
    - name: Tag Release Images
      run: |
        docker tag ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:${{ steps.semver.outputs.major }}
        docker tag ghcr.io/requarks/wiki-core:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-core:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
        docker tag ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:${{ steps.semver.outputs.major }}
        docker tag ghcr.io/requarks/wiki-ui:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-ui:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
        docker tag ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:${{env.BUILD_VERSION}}
        docker tag ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:${{ steps.semver.outputs.major }}
        docker tag ghcr.io/requarks/wiki-combo:beta-${{env.BUILD_VERSION}} ghcr.io/requarks/wiki-combo:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
    - name: Push Release Images
      run: |
        docker push ghcr.io/requarks/wiki-core:${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-core:${{ steps.semver.outputs.major }}
        docker push ghcr.io/requarks/wiki-core:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
        docker push ghcr.io/requarks/wiki-ui:${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-ui:${{ steps.semver.outputs.major }}
        docker push ghcr.io/requarks/wiki-ui:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
        docker push ghcr.io/requarks/wiki-combo:${{env.BUILD_VERSION}}
        docker push ghcr.io/requarks/wiki-combo:${{ steps.semver.outputs.major }}
        docker push ghcr.io/requarks/wiki-combo:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}
    - name: Update Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitBody: true
        omitName: true
        replacesArtifacts: false
        draft: false
        prerelease: false
        tag: ${{env.BUILD_VERSION}}
        token: ${{ secrets.GITHUB_TOKEN }}
